name: kuissi
description: A simple quiz app using Flutter and REST API
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.0
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/   # kalau kamu nanti pakai gambar

  fonts:
    - family: Arial
      fonts:
        - asset: assets/fonts/PlusJakartaSans-VariableFont_wght.ttf   # opsional, kalau kamu pakai font custom
